apiVersion: v1
kind: Secret
metadata:
  name: dwflynn-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: dwflynn-repo
  url: registry-1.docker.io/dwflynn
  enableOCI: "true"
  type: helm
