apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: faces-app-of-apps
  namespace: argocd
spec:
  source:
    path: argocd/applications
    repoURL: 'https://github.com/kflynn/real-world-argo-linkerd.git'
    targetRevision: main
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
