apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: faces-demo
  namespace: argocd
spec:
  source:
    path: argocd/applications
    repoURL: 'https://github.com/reginapizza/argocd-linkerd-demo-2'
    targetRevision: master
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true