apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: emissary-crds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: registry-1.docker.io/dwflynn
    chart: emissary-ingress-crds-chart
    targetRevision: 3.9.1
  destination:
    namespace: emissary-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}
