apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # Without the resources-finalizer.argocd.argoproj.io finalizer, deleting an application will not delete the resources it manages. 
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: cert-manager-app
  # the namespace here must match the namespace of our Argo CD instance
  namespace: argocd
spec:
  source:
    path: apps/cert-manager
    repoURL: 'https://github.com/reginapizza/argocd-linkerd-demo-2.git'
    targetRevision: master
  destination:
    namespace: cert-manager
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true