apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # Without the resources-finalizer.argocd.argoproj.io finalizer, deleting an application will not delete the resources it manages.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: emissary
  # the namespace here must match the namespace of our Argo CD instance
  namespace: argocd
spec:
  destination:
    namespace: emissary
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/emissary
    repoURL: 'https://github.com/kflynn/argocd-linkerd-demo-2.git'
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
