apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-issuer
  namespace: cert-manager
spec:
  vault:
    path: pki/root/sign-intermediate
    server: http://%VAULTADDR%:8200
    auth:
      tokenSecretRef:
         name: vault-pki-token
         key: token
