apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-crds
  namespace: argocd
spec:
  project: demo # why is this demo and not default? 
  source:
    chart: linkerd-crds
    repoURL: https://helm.linkerd.io/stable
    targetRevision: 1.8.0
    helm:
  destination:
    namespace: linkerd
    server: https://kubernetes.default.svc
